site_name: Airport Opera

site_url: https://devleaks.github.io/emitpy
repo_url: https://github.com/devleaks/emitpy
site_description: Documentation for Emitpy ADS-B Track Generator for Airports
copyright: |
  Copyright &copy; 2018 - 2024 <a href="https://github.com/devleaks"  target="_blank" rel="noopener">Pierre M</a>

theme:
  name: material # Must use Material theme
  # custom_dir: docs/theme # If you have overrides, specify where to find them
  icon:
    logo: material/airplane
  palette:
    scheme: dracula # This is how to enables the Dracula theme for dark. For light, it will use default Material with some tweaks.
    primary: deep purple # Primary colors
    accent: orange # accent color
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotations
  pymdownx:
    sponsor: "https://github.com/sponsors/facelessuser"

nav:
  - Home:
      - Airport Opera: index.md
      - Emitpy: emitpy/Emitpy – ADS-B Track Generator.md
  - Airport Opera:
      - Home: opera/Opera – Airport Operational Effectiveness Assessment.md
      - Rules: opera/Rule.md
      - Vehicle: opera/Vehicle.md
      - Areas of Interest: opera/Areas of Interest.md
  - Emitpy:
      - Home: emitpy/Emitpy – ADS-B Track Generator.md
      - Managed Airport: emitpy/Airport/Managed Airport.md
      - Flight: emitpy/Flight/Flight.md
      - Service: emitpy/Service/Service.md
      - Data Sources: emitpy/Emitpy – Data Sources.md

# Extensions
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format { kwds: { mode: generic, tag: pre } }
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
      types:
        - name: details-new
          class: new
        - name: details-settings
          class: settings
        - name: details-note
          class: note
        - name: details-abstract
          class: abstract
        - name: details-info
          class: info
        - name: details-tip
          class: tip
        - name: details-success
          class: success
        - name: details-question
          class: question
        - name: details-warning
          class: warning
        - name: details-failure
          class: failure
        - name: details-danger
          class: danger
        - name: details-bug
          class: bug
        - name: details-example
          class: example
        - name: details-quote
          class: quote
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }

plugins:
  - search
  - roamlinks
  - callouts
  - mkdocs_pymdownx_material_extras
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
